# Generated by Django 2.0.3 on 2018-03-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180330_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='efforts',
            field=models.DurationField(null=True),
        ),
    ]
