# Generated by Django 2.0.3 on 2018-03-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.CharField(choices=[('1', 'On Due'), ('2', 'Overdue'), ('3', 'Done')], default=1, max_length=7, null=True),
        ),
    ]
