# Generated by Django 2.0.3 on 2018-03-31 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180331_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='efforts',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.CharField(choices=[('1', 'On Due'), ('2', 'Overdue'), ('3', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project'),
        ),
    ]
