# Generated by Django 2.0.3 on 2018-04-02 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_invites', to='register.UserProfile')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='made_invites', to='register.UserProfile')),
            ],
        ),
    ]
