# Generated by Django 2.0.3 on 2018-04-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180402_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
