# Generated by Django 2.0.3 on 2018-03-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('register', '0002_auto_20180329_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
