# Generated by Django 2.0.3 on 2018-04-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_delete_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img0',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
