# Generated by Django 2.0.3 on 2018-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180402_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='friends',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_userprofile_friends_+', to='register.UserProfile'),
        ),
    ]
