# Generated by Django 2.0.3 on 2018-04-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_userprofile_img0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='img0',
            new_name='img',
        ),
    ]
