# Generated by Django 2.0.3 on 2018-04-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20180403_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='static/core/avatar/blank_profile.png', upload_to='avatar'),
        ),
    ]
